name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t mlops-tp1 .
    - run: docker tag mlops-tp1 glalire/mlops-tp1
    - run: docker login -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push glalire/mlops-tp1
    - run: ssh ubuntu@17.2.2.1 "docker compose pull glalire/mlops-tp1"
