name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t mlops-tp1 .
    - run: docker tag mlops-tp1 ${{ secrets.DOCKER_USER }}/mlops-tp1
    - run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push glalire/mlops-tp1
    - run: sudo apt-get install sshpass
    - run: sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_IP }} "docker pull ${{ secrets.DOCKER_USER }}/mlops-tp1 && docker run -d ${{ secrets.DOCKER_USER }}/mlops-tp1"
